# The Unconquerables of Open Access

## Merging MEDLINE journals with Sherpa / Romeo data

Project for the EAHIL conference 2023 : https://eahil2023.org/  
Authors : **Floriane Muller & Pablo Iriarte**, University of Geneva  
Last update : 19.04.2023  

This notebook is used to merge the Sherpa/Romeo data obtained by API and NLM journals data.

### Sources

1. **Sherpa/Romeo parsed data**
2. **Pubmed journals data**

In [1]:
import pandas as pd
import csv
# afficher toutes les colonnes
pd.set_option('display.max_columns', None)

## Import Pubmed data

In [2]:
pubmed = pd.read_csv('data/sources/nlm/lsi2023_medline_issns.tsv', dtype={'NlmUniqueID': 'str'}, encoding='utf-8', header=0, sep='\t')
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730

## Import Sherpa data

In [3]:
sherpa_policies = pd.read_csv('data/temp/2023/sherpa_policies.tsv', encoding='utf-8', header=0, sep='\t')
sherpa_policies

C:\Users\iriarte\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (0,2,17,30,38) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,NlmUniqueID,title_sherpa,issne_sherpa,issnp_sherpa,url,publisher_id,publisher_country,publisher_type,publisher_url,publisher_name,sherpa_id,sherpa_uri,open_access_prohibited,additional_oa_fee,article_version,license,embargo,prerequisites,prerequisite_funders,prerequisite_funders_name,prerequisite_funders_fundref,prerequisite_funders_ror,prerequisite_funders_country,prerequisite_funders_url,prerequisite_funders_sherpa_id,prerequisite_subjects,location,locations_ir,locations_not_ir,named_repository,named_academic_social_network,copyright_owner,publisher_deposit,archiving,conditions,public_notes,sherpa_created,sherpa_last_modified,prerequisites_phrases,id
0,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,no,no,submitted,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,any_repository ; any_website ; authors_homepag...,Any Repository ; Any Website ; Institutional R...,Author's Homepage ; Non-Commercial Subject Rep...,NaN,NaN,NaN,NaN,True,Prior to acceptance ; Must be accompanied by a...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,1
1,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,no,no,accepted,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,institutional_repository ; non_commercial_subj...,Institutional Repository,Non-Commercial Subject Repository,NaN,NaN,NaN,NaN,True,Published source must be acknowledged ; Must l...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,2
2,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,no,no,accepted,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,authors_homepage,NaN,Author's Homepage,NaN,NaN,NaN,NaN,False,Published source must be acknowledged ; Must l...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,3
3,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/3302,no,yes,published,cc_by_nc,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,any_website ; named_repository ; non_commercia...,Any Website ; Non-Commercial Institutional Rep...,PubMed Central ; Non-Commercial Subject Reposi...,PubMed Central,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,4
4,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/3302,no,yes,published,cc_by_nc_nd,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,any_website ; named_repository ; non_commercia...,Any Website ; Non-Commercial Institutional Rep...,PubMed Central ; Non-Commercial Subject Reposi...,PubMed Central,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49562,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Medical Research Council (MRC),http://dx.doi.org/10.13039/501100000265,https://ror.org/03x94j517,gb,http://www.mrc.ac.uk/index.htm,705.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49563
49563,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Motor Neuron Disease Association (MND Associat...,http://dx.doi.org/10.13039/501100000406,https://ror.org/02gq0fg61,gb,http://www.mndassociation.org/,562.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49564
49564,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Parkinson's UK,http://dx.doi.org/10.13039/501100000304,https://ror.org/02417p338,gb,http://www.parkinsons.org.uk/,411.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49565
49565,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Telethon Foundation,http://dx.doi.org/10.13039/501100002426,https://ror.org/04xraxn18,it,https://www.telethon.it/en/,325.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49566
49566,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,National Institute for Health and Care Researc...,10.13039/501100000272,https://ror.org/0187kwz08,gb,https://www.nihr.ac.uk/,1333.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49567

### Calculating Sherpa categories

In [4]:
sherpa_policies_oa = sherpa_policies.loc[sherpa_policies['open_access_prohibited'] == 'no'][['NlmUniqueID', 'sherpa_id', 'article_version']]
sherpa_policies_oa

      NlmUniqueID  sherpa_id article_version
0         9015384       1406       submitted
1         9015384       1406        accepted
2         9015384       1406        accepted
3         9015384       1406       published
4         9015384       1406       published
...           ...        ...             ...
49562     9435608      15919       published
49563     9435608      15919       published
49564     9435608      15919       published
49565     9435608      15919       published
49566     9435608      15919       published

[49567 rows x 3 columns]

In [5]:
# dedup
sherpa_policies_oa_dedup = sherpa_policies_oa.drop_duplicates(subset='NlmUniqueID')
sherpa_policies_oa_dedup

      NlmUniqueID  sherpa_id article_version
0         9015384       1406       submitted
6       101269322      10921        accepted
7       101223209      16180       submitted
11      100960111      16179       submitted
15      101674571      35942       submitted
...           ...        ...             ...
49504   101477604      15891       submitted
49525       33370      10878        accepted
49528     9508901      10879        accepted
49531      413645      10884        accepted
49534     9435608      15919       submitted

[4378 rows x 3 columns]

In [6]:
# add OA category (all article versions included)
sherpa_policies_oa_dedup['sherpa_has_oa_path'] = 'yes'
sherpa_policies_oa_dedup

C:\Users\iriarte\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

      NlmUniqueID  sherpa_id article_version sherpa_has_oa_path
0         9015384       1406       submitted                yes
6       101269322      10921        accepted                yes
7       101223209      16180       submitted                yes
11      100960111      16179       submitted                yes
15      101674571      35942       submitted                yes
...           ...        ...             ...                ...
49504   101477604      15891       submitted                yes
49525       33370      10878        accepted                yes
49528     9508901      10879        accepted                yes
49531      413645      10884        accepted                yes
49534     9435608      15919       submitted                yes

[4378 rows x 4 columns]

In [7]:
# clean article version after dedup
del sherpa_policies_oa_dedup['article_version']
sherpa_policies_oa_dedup

      NlmUniqueID  sherpa_id sherpa_has_oa_path
0         9015384       1406                yes
6       101269322      10921                yes
7       101223209      16180                yes
11      100960111      16179                yes
15      101674571      35942                yes
...           ...        ...                ...
49504   101477604      15891                yes
49525       33370      10878                yes
49528     9508901      10879                yes
49531      413645      10884                yes
49534     9435608      15919                yes

[4378 rows x 3 columns]

In [8]:
# archiving for published or accepted versions and not additional_oa_fee
# if needed (sherpa_policies['prerequisite_funders'].isna())
sherpa_policies_ir = sherpa_policies.loc[(sherpa_policies['archiving'] == True) & ((sherpa_policies['article_version'] == 'published') | (sherpa_policies['article_version'] == 'accepted')) & (sherpa_policies['additional_oa_fee'] != 'yes')][['NlmUniqueID', 'embargo', 'license', 'conditions', 'article_version', 'sherpa_created' , 'sherpa_last_modified', 'sherpa_id']]
sherpa_policies_ir

,NlmUniqueID,embargo,license,conditions,article_version,sherpa_created,sherpa_last_modified,sherpa_id
1,9015384,24,NaN,Published source must be acknowledged ; Must l...,accepted,2010-07-15 16:04:39,2022-07-26 10:25:23,1406
9,101223209,12,bespoke_license,Published source must be acknowledged ; Must l...,accepted,2010-09-15 13:16:19,2023-01-05 14:55:40,16180
13,100960111,12,bespoke_license,Published source must be acknowledged ; Must l...,accepted,2010-09-15 13:16:19,2023-01-05 14:55:40,16179
17,101674571,12,bespoke_license,Published source must be acknowledged ; Must l...,accepted,2019-06-14 10:53:31,2023-01-05 14:56:07,35942
20,9418450,12,NaN,Publisher source must be acknowledged with cit...,accepted,2010-08-03 16:45:39,2022-06-22 10:45:44,6769
...,...,...,...,...,...,...,...,...
49544,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919
49545,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919
49546,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919
49547,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919
49548,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919

In [9]:
# add embargo columns for each version
sherpa_policies_ir.loc[sherpa_policies_ir['article_version'] == 'published', 'embargo_published_version'] = sherpa_policies_ir['embargo']
sherpa_policies_ir.loc[sherpa_policies_ir['article_version'] == 'accepted', 'embargo_accepted_version'] = sherpa_policies_ir['embargo']
sherpa_policies_ir

,NlmUniqueID,embargo,license,conditions,article_version,sherpa_created,sherpa_last_modified,sherpa_id,embargo_published_version,embargo_accepted_version
1,9015384,24,NaN,Published source must be acknowledged ; Must l...,accepted,2010-07-15 16:04:39,2022-07-26 10:25:23,1406,NaN,24.0
9,101223209,12,bespoke_license,Published source must be acknowledged ; Must l...,accepted,2010-09-15 13:16:19,2023-01-05 14:55:40,16180,NaN,12.0
13,100960111,12,bespoke_license,Published source must be acknowledged ; Must l...,accepted,2010-09-15 13:16:19,2023-01-05 14:55:40,16179,NaN,12.0
17,101674571,12,bespoke_license,Published source must be acknowledged ; Must l...,accepted,2019-06-14 10:53:31,2023-01-05 14:56:07,35942,NaN,12.0
20,9418450,12,NaN,Publisher source must be acknowledged with cit...,accepted,2010-08-03 16:45:39,2022-06-22 10:45:44,6769,NaN,12.0
...,...,...,...,...,...,...,...,...,...,...
49544,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919,NaN,12.0
49545,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919,NaN,12.0
49546,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919,NaN,12.0
49547,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919,NaN,12.0
49548,9435608,12,cc_by_nc_nd,Must link to publisher version with DOI,accepted,2010-09-14 14:06:06,2022-07-26 14:26:43,15919,NaN,12.0

In [10]:
sherpa_policies_ir['article_version'].value_counts()

accepted     8979
published    4439
Name: article_version, dtype: int64

In [11]:
sherpa_policies_ir_max_published = sherpa_policies_ir[['NlmUniqueID', 'sherpa_id', 'embargo_published_version']].sort_values(by=['NlmUniqueID', 'embargo_published_version'], ascending=[True, True])
sherpa_policies_ir_max_accepted = sherpa_policies_ir[['NlmUniqueID', 'sherpa_id', 'embargo_accepted_version']].sort_values(by=['NlmUniqueID', 'embargo_accepted_version'], ascending=[True, True])
sherpa_policies_ir_max_published = sherpa_policies_ir_max_published.drop_duplicates(subset='NlmUniqueID')
sherpa_policies_ir_max_accepted = sherpa_policies_ir_max_accepted.drop_duplicates(subset='NlmUniqueID')

In [12]:
sherpa_policies_ir_max_published

            NlmUniqueID  sherpa_id  embargo_published_version
49527             33370      10878                        NaN
49374            105072      13286                        NaN
49299            110674      11416                        NaN
49191            366151      16570                        NaN
49533            413645      10884                        NaN
...                 ...        ...                        ...
3039   9918402287906676      41350                        0.0
11108  9918418288306676       3945                        NaN
33848  9918470777806676       3973                        NaN
17901  9918487342606676       7349                        NaN
4383   9918522188506676      29978                        0.0

[4281 rows x 3 columns]

In [13]:
# dedup and keep min embargo values
sherpa_policies_ir_id = sherpa_policies_ir[['NlmUniqueID', 'embargo']].sort_values(by=['NlmUniqueID', 'embargo'], ascending=[True, True])
sherpa_policies_ir_dedup = sherpa_policies_ir_id.drop_duplicates(subset='NlmUniqueID')
sherpa_policies_ir_dedup

            NlmUniqueID  embargo
49527             33370       12
49375            105072       12
49299            110674       12
49191            366151       12
49533            413645       12
...                 ...      ...
3039   9918402287906676        0
11110  9918418288306676        6
33850  9918470777806676        6
17901  9918487342606676        0
4383   9918522188506676        0

[4281 rows x 2 columns]

In [14]:
# merge with min values for each version
sherpa_policies_ir_dedup = sherpa_policies_ir_dedup.merge(sherpa_policies_ir_max_published, on='NlmUniqueID', how='left')
sherpa_policies_ir_dedup = sherpa_policies_ir_dedup.merge(sherpa_policies_ir_max_accepted, on='NlmUniqueID', how='left')
sherpa_policies_ir_dedup

,NlmUniqueID,embargo,sherpa_id_x,embargo_published_version,sherpa_id_y,embargo_accepted_version
0,33370,12,10878,NaN,10878,12.0
1,105072,12,13286,NaN,13286,12.0
2,110674,12,11416,NaN,11416,12.0
3,366151,12,16570,NaN,16570,12.0
4,413645,12,10884,NaN,10884,12.0
...,...,...,...,...,...,...
4276,9918402287906676,0,41350,0.0,41350,NaN
4277,9918418288306676,6,3945,NaN,3945,6.0
4278,9918470777806676,6,3973,NaN,3973,6.0
4279,9918487342606676,0,7349,NaN,7349,0.0
4280,9918522188506676,0,29978,0.0,29978,0.0

In [15]:
# rename sherpa_id
sherpa_policies_ir_dedup = sherpa_policies_ir_dedup.rename(columns={'sherpa_id_x' : 'sherpa_id'})
del sherpa_policies_ir_dedup['sherpa_id_y']

In [16]:
sherpa_policies_ir_dedup.loc[(sherpa_policies_ir_dedup['embargo_published_version'] > 0) & (sherpa_policies_ir_dedup['embargo_accepted_version'] > 0)]

,NlmUniqueID,embargo,sherpa_id,embargo_published_version,embargo_accepted_version
65,0052457,6,14670,6.0,12.0
195,0243705,6,14671,6.0,12.0
382,0373125,12,13754,12.0,12.0
403,0375040,12,14394,12.0,12.0
410,0375362,12,26766,12.0,12.0
1495,101313252,6,13588,24.0,6.0
2455,7609576,12,13755,12.0,12.0
2674,8006258,12,32836,12.0,12.0
3050,8701744,12,14668,12.0,12.0

In [17]:
# add green category
sherpa_policies_ir_dedup['oa_status'] = 'green'
sherpa_policies_ir_dedup

,NlmUniqueID,embargo,sherpa_id,embargo_published_version,embargo_accepted_version,oa_status
0,33370,12,10878,NaN,12.0,green
1,105072,12,13286,NaN,12.0,green
2,110674,12,11416,NaN,12.0,green
3,366151,12,16570,NaN,12.0,green
4,413645,12,10884,NaN,12.0,green
...,...,...,...,...,...,...
4276,9918402287906676,0,41350,0.0,NaN,green
4277,9918418288306676,6,3945,NaN,6.0,green
4278,9918470777806676,6,3973,NaN,6.0,green
4279,9918487342606676,0,7349,NaN,0.0,green
4280,9918522188506676,0,29978,0.0,0.0,green

In [18]:
sherpa_policies_oa_fees = sherpa_policies.loc[(sherpa_policies['open_access_prohibited'] == 'no') & (sherpa_policies['additional_oa_fee'] == 'yes') & (sherpa_policies['article_version'] == 'published')][['NlmUniqueID', 'sherpa_id', 'embargo', 'license', 'conditions', 'prerequisite_funders', 'open_access_prohibited', 'additional_oa_fee']]
sherpa_policies_oa_fees

,NlmUniqueID,sherpa_id,embargo,license,conditions,prerequisite_funders,open_access_prohibited,additional_oa_fee
3,9015384,1406,0,cc_by_nc,Published source must be acknowledged with cit...,NaN,no,yes
4,9015384,1406,0,cc_by_nc_nd,Published source must be acknowledged with cit...,NaN,no,yes
5,9015384,1406,0,cc_by,Published source must be acknowledged with cit...,NaN,no,yes
10,101223209,16180,0,cc_by,NaN,NaN,no,yes
14,100960111,16179,0,cc_by,NaN,NaN,no,yes
...,...,...,...,...,...,...,...,...
49562,9435608,15919,0,cc_by,Published source must be acknowledged with cit...,True,no,yes
49563,9435608,15919,0,cc_by,Published source must be acknowledged with cit...,True,no,yes
49564,9435608,15919,0,cc_by,Published source must be acknowledged with cit...,True,no,yes
49565,9435608,15919,0,cc_by,Published source must be acknowledged with cit...,True,no,yes
49566,9435608,15919,0,cc_by,Published source must be acknowledged with cit...,True,no,yes

In [19]:
# dedup
sherpa_policies_oa_fees_id = sherpa_policies_oa_fees[['NlmUniqueID', 'sherpa_id', 'additional_oa_fee']]
# sort_values(by=['NlmUniqueID'])
sherpa_policies_oa_fees_id_dedup = sherpa_policies_oa_fees_id.drop_duplicates(subset='NlmUniqueID')
sherpa_policies_oa_fees_id_dedup

      NlmUniqueID  sherpa_id additional_oa_fee
3         9015384       1406               yes
10      101223209      16180               yes
14      100960111      16179               yes
18      101674571      35942               yes
21        9418450       6769               yes
...           ...        ...               ...
49462     9101000      16572               yes
49483   101528275      15856               yes
49503     9312666      13335               yes
49507   101477604      15891               yes
49549     9435608      15919               yes

[3423 rows x 3 columns]

In [20]:
# add hybrid category
sherpa_policies_oa_fees_id_dedup['oa_status'] = 'hybrid or gold'
sherpa_policies_oa_fees_id_dedup

C:\Users\iriarte\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

      NlmUniqueID  sherpa_id additional_oa_fee       oa_status
3         9015384       1406               yes  hybrid or gold
10      101223209      16180               yes  hybrid or gold
14      100960111      16179               yes  hybrid or gold
18      101674571      35942               yes  hybrid or gold
21        9418450       6769               yes  hybrid or gold
...           ...        ...               ...             ...
49462     9101000      16572               yes  hybrid or gold
49483   101528275      15856               yes  hybrid or gold
49503     9312666      13335               yes  hybrid or gold
49507   101477604      15891               yes  hybrid or gold
49549     9435608      15919               yes  hybrid or gold

[3423 rows x 4 columns]

In [21]:
# export csv
sherpa_policies_oa_dedup.to_csv('data/temp/2023/sherpa_policies_oa_dedup.tsv', sep='\t', encoding='utf-8', index=False)
sherpa_policies_ir_dedup.to_csv('data/temp/2023/sherpa_policies_ir_dedup.tsv', sep='\t', encoding='utf-8', index=False)
sherpa_policies_ir.to_csv('data/temp/2023/sherpa_policies_ir.tsv', sep='\t', encoding='utf-8', index=False)
sherpa_policies_oa_fees_id_dedup.to_csv('data/temp/2023/sherpa_policies_oa_fees_id_dedup.tsv', sep='\t', encoding='utf-8', index=False)

In [22]:
sherpa_policies_oa_dedup.to_excel('data/temp/2023/sherpa_policies_oa_dedup.xlsx', index=False)
sherpa_policies_ir_dedup.to_excel('data/temp/2023/sherpa_policies_ir_dedup.xlsx', index=False)
sherpa_policies_ir.to_excel('data/temp/2023/sherpa_policies_ir.xlsx', index=False)
sherpa_policies_oa_fees_id_dedup.to_excel('data/temp/2023/sherpa_policies_oa_fees_id_dedup.xlsx', index=False)

## Adding OA categories

In [23]:
sherpa_oa = pd.read_csv('data/temp/2023/sherpa_policies_oa_dedup.tsv', encoding='utf-8', header=0, sep='\t')
sherpa_oa

     NlmUniqueID  sherpa_id sherpa_has_oa_path
0        9015384       1406                yes
1      101269322      10921                yes
2      101223209      16180                yes
3      100960111      16179                yes
4      101674571      35942                yes
...          ...        ...                ...
4373   101477604      15891                yes
4374       33370      10878                yes
4375     9508901      10879                yes
4376      413645      10884                yes
4377     9435608      15919                yes

[4378 rows x 3 columns]

In [24]:
sherpa_green = pd.read_csv('data/temp/2023/sherpa_policies_ir_dedup.tsv', encoding='utf-8', header=0, sep='\t')
sherpa_green

,NlmUniqueID,embargo,sherpa_id,embargo_published_version,embargo_accepted_version,oa_status
0,33370,12,10878,NaN,12.0,green
1,105072,12,13286,NaN,12.0,green
2,110674,12,11416,NaN,12.0,green
3,366151,12,16570,NaN,12.0,green
4,413645,12,10884,NaN,12.0,green
...,...,...,...,...,...,...
4276,9918402287906676,0,41350,0.0,NaN,green
4277,9918418288306676,6,3945,NaN,6.0,green
4278,9918470777806676,6,3973,NaN,6.0,green
4279,9918487342606676,0,7349,NaN,0.0,green
4280,9918522188506676,0,29978,0.0,0.0,green

In [25]:
sherpa_hybrid = pd.read_csv('data/temp/2023/sherpa_policies_oa_fees_id_dedup.tsv', encoding='utf-8', header=0, sep='\t')
sherpa_hybrid

     NlmUniqueID  sherpa_id additional_oa_fee       oa_status
0        9015384       1406               yes  hybrid or gold
1      101223209      16180               yes  hybrid or gold
2      100960111      16179               yes  hybrid or gold
3      101674571      35942               yes  hybrid or gold
4        9418450       6769               yes  hybrid or gold
...          ...        ...               ...             ...
3418     9101000      16572               yes  hybrid or gold
3419   101528275      15856               yes  hybrid or gold
3420     9312666      13335               yes  hybrid or gold
3421   101477604      15891               yes  hybrid or gold
3422     9435608      15919               yes  hybrid or gold

[3423 rows x 4 columns]

In [26]:
# merge oa
pubmed = pd.merge(pubmed, sherpa_oa, on='NlmUniqueID', how='left')
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN,sherpa_id,sherpa_has_oa_path
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674,1406.0,yes
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126,NaN,NaN
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776,10921.0,yes
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239,NaN,NaN
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416,16180.0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003,NaN,NaN
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720,15919.0,yes
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378,2555.0,yes
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334,6.0,yes
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730,2242.0,yes

In [27]:
# merge green
pubmed = pd.merge(pubmed, sherpa_green, on='NlmUniqueID', how='left')
pubmed = pubmed.rename(columns={'oa_status' : 'sherpa_oa_green'})
pubmed.loc[(pubmed['sherpa_oa_green'] == 'green'), 'sherpa_oa_green'] = 'yes'
# keep all sherpa ids
pubmed['sherpa_id'] = pubmed['sherpa_id_x']
pubmed.loc[pubmed['sherpa_id'].isna(), 'sherpa_id'] = pubmed['sherpa_id_y']
del pubmed['sherpa_id_x']
del pubmed['sherpa_id_y']
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN,sherpa_has_oa_path,embargo,embargo_published_version,embargo_accepted_version,sherpa_oa_green,sherpa_id
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674,yes,24.0,NaN,24.0,yes,1406.0
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126,NaN,NaN,NaN,NaN,NaN,NaN
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776,yes,NaN,NaN,NaN,NaN,10921.0
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239,NaN,NaN,NaN,NaN,NaN,NaN
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416,yes,12.0,NaN,12.0,yes,16180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003,NaN,NaN,NaN,NaN,NaN,NaN
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720,yes,12.0,NaN,12.0,yes,15919.0
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378,yes,12.0,NaN,12.0,yes,2555.0
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334,yes,NaN,NaN,NaN,NaN,6.0
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730,yes,6.0,NaN,6.0,yes,2242.0

In [28]:
# merge hybrid
pubmed = pd.merge(pubmed, sherpa_hybrid, on='NlmUniqueID', how='left')
# keep all sherpa ids
pubmed['sherpa_id'] = pubmed['sherpa_id_x']
pubmed.loc[pubmed['sherpa_id'].isna(), 'sherpa_id'] = pubmed['sherpa_id_y']
del pubmed['sherpa_id_x']
del pubmed['sherpa_id_y']
del pubmed['oa_status']
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN,sherpa_has_oa_path,embargo,embargo_published_version,embargo_accepted_version,sherpa_oa_green,additional_oa_fee,sherpa_id
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674,yes,24.0,NaN,24.0,yes,yes,1406.0
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776,yes,NaN,NaN,NaN,NaN,NaN,10921.0
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416,yes,12.0,NaN,12.0,yes,yes,16180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720,yes,12.0,NaN,12.0,yes,yes,15919.0
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378,yes,12.0,NaN,12.0,yes,yes,2555.0
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334,yes,NaN,NaN,NaN,NaN,yes,6.0
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730,yes,6.0,NaN,6.0,yes,yes,2242.0

In [29]:
# sherpa not OA
sherpa_policies['open_access_prohibited'].value_counts()

no    49567
Name: open_access_prohibited, dtype: int64

In [30]:
# sherpa not OA
sherpa_not_oa = sherpa_policies.loc[sherpa_policies['open_access_prohibited'] != 'no']
sherpa_not_oa

Empty DataFrame
Columns: [NlmUniqueID, title_sherpa, issne_sherpa, issnp_sherpa, url, publisher_id, publisher_country, publisher_type, publisher_url, publisher_name, sherpa_id, sherpa_uri, open_access_prohibited, additional_oa_fee, article_version, license, embargo, prerequisites, prerequisite_funders, prerequisite_funders_name, prerequisite_funders_fundref, prerequisite_funders_ror, prerequisite_funders_country, prerequisite_funders_url, prerequisite_funders_sherpa_id, prerequisite_subjects, location, locations_ir, locations_not_ir, named_repository, named_academic_social_network, copyright_owner, publisher_deposit, archiving, conditions, public_notes, sherpa_created, sherpa_last_modified, prerequisites_phrases, id]
Index: []

## Adding Sherpa journal / publisher data

In [31]:
sherpa_policies

,NlmUniqueID,title_sherpa,issne_sherpa,issnp_sherpa,url,publisher_id,publisher_country,publisher_type,publisher_url,publisher_name,sherpa_id,sherpa_uri,open_access_prohibited,additional_oa_fee,article_version,license,embargo,prerequisites,prerequisite_funders,prerequisite_funders_name,prerequisite_funders_fundref,prerequisite_funders_ror,prerequisite_funders_country,prerequisite_funders_url,prerequisite_funders_sherpa_id,prerequisite_subjects,location,locations_ir,locations_not_ir,named_repository,named_academic_social_network,copyright_owner,publisher_deposit,archiving,conditions,public_notes,sherpa_created,sherpa_last_modified,prerequisites_phrases,id
0,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,no,no,submitted,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,any_repository ; any_website ; authors_homepag...,Any Repository ; Any Website ; Institutional R...,Author's Homepage ; Non-Commercial Subject Rep...,NaN,NaN,NaN,NaN,True,Prior to acceptance ; Must be accompanied by a...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,1
1,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,no,no,accepted,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,institutional_repository ; non_commercial_subj...,Institutional Repository,Non-Commercial Subject Repository,NaN,NaN,NaN,NaN,True,Published source must be acknowledged ; Must l...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,2
2,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,no,no,accepted,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,authors_homepage,NaN,Author's Homepage,NaN,NaN,NaN,NaN,False,Published source must be acknowledged ; Must l...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,3
3,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/3302,no,yes,published,cc_by_nc,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,any_website ; named_repository ; non_commercia...,Any Website ; Non-Commercial Institutional Rep...,PubMed Central ; Non-Commercial Subject Reposi...,PubMed Central,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,4
4,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/3302,no,yes,published,cc_by_nc_nd,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,any_website ; named_repository ; non_commercia...,Any Website ; Non-Commercial Institutional Rep...,PubMed Central ; Non-Commercial Subject Reposi...,PubMed Central,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-07-15 16:04:39,2022-07-26 10:25:23,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49562,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Medical Research Council (MRC),http://dx.doi.org/10.13039/501100000265,https://ror.org/03x94j517,gb,http://www.mrc.ac.uk/index.htm,705.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49563
49563,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Motor Neuron Disease Association (MND Associat...,http://dx.doi.org/10.13039/501100000406,https://ror.org/02gq0fg61,gb,http://www.mndassociation.org/,562.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49564
49564,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Parkinson's UK,http://dx.doi.org/10.13039/501100000304,https://ror.org/02417p338,gb,http://www.parkinsons.org.uk/,411.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49565
49565,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,Telethon Foundation,http://dx.doi.org/10.13039/501100002426,https://ror.org/04xraxn18,it,https://www.telethon.it/en/,325.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49566
49566,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/3323,no,yes,published,cc_by,0,NaN,True,National Institute for Health and Care Researc...,10.13039/501100000272,https://ror.org/0187kwz08,gb,https://www.nihr.ac.uk/,1333.0,NaN,any_repository ; institutional_repository ; na...,Any Repository ; Institutional Repository,PubMed Central ; Research for Development Repo...,PubMed Central ; Research for Development Repo...,NaN,NaN,disciplinary (PubMed Central) ;,True,Published source must be acknowledged with cit...,NaN,2010-09-14 14:06:06,2022-07-26 14:26:43,NaN,49567

In [32]:
# dedup
sherpa_policies_dedup = sherpa_policies[['NlmUniqueID', 'title_sherpa', 'issne_sherpa', 'issnp_sherpa', 'url', 'publisher_id', 'publisher_country', 'publisher_type', 'publisher_url', 'publisher_name', 'sherpa_id', 'sherpa_uri', 'sherpa_created', 'sherpa_last_modified']].drop_duplicates(subset='NlmUniqueID')
sherpa_policies_dedup

,NlmUniqueID,title_sherpa,issne_sherpa,issnp_sherpa,url,publisher_id,publisher_country,publisher_type,publisher_url,publisher_name,sherpa_id,sherpa_uri,sherpa_created,sherpa_last_modified
0,9015384,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406,https://v2.sherpa.ac.uk/id/publisher_policy/1112,2010-07-15 16:04:39,2022-07-26 10:25:23
6,101269322,AACN Advanced Critical Care,1559-7776,1559-7768,http://acc.aacnjournals.org/,663,us,society_publisher,https://www.aacn.org/,American Association of Critical Care Nurses,10921,https://v2.sherpa.ac.uk/id/publisher_policy/663,2010-08-24 15:05:09,2022-07-08 08:42:33
7,101223209,AAPS Journal,NaN,1550-7416,http://link.springer.com/journal/12248,313,us,client_organisation,https://www.aaps.org/home,American Association of Pharmaceutical Scientists,16180,https://v2.sherpa.ac.uk/id/publisher_policy/3291,2010-09-15 13:16:19,2023-01-05 14:55:40
11,100960111,AAPS PharmSciTech,1530-9932,NaN,http://link.springer.com/journal/12249,3291,gb,commercial_publisher,https://www.springernature.com/gp/products/jou...,Springer,16179,https://v2.sherpa.ac.uk/id/publisher_policy/3291,2010-09-15 13:16:19,2023-01-05 14:55:40
15,101674571,Abdominal Radiology,2366-0058,2366-004X,https://www.springer.com/journal/261,3291,gb,commercial_publisher,https://www.springernature.com/gp/products/jou...,Springer,35942,https://v2.sherpa.ac.uk/id/publisher_policy/3291,2019-06-14 10:53:31,2023-01-05 14:56:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49504,101477604,"Zeitschrift für Evidenz, Fortbildung und Quali...",NaN,1865-9217,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15891,https://v2.sherpa.ac.uk/id/publisher_policy/2823,2010-09-14 13:53:39,2022-07-26 14:27:23
49525,33370,Zeitschrift für Gastroenterologie,NaN,0044-2771,https://www.thieme.de/de/zeitschrift-gastroent...,257,de,commercial_publisher,http://www.thieme.de/,Georg Thieme Verlag,10878,https://v2.sherpa.ac.uk/id/publisher_policy/257,2010-08-24 13:51:41,2022-09-21 14:12:10
49528,9508901,Zeitschrift für Geburtshilfe und Neonatologie,NaN,0948-2393,https://www.thieme-connect.com/products/ejourn...,257,de,commercial_publisher,http://www.thieme.de/,Georg Thieme Verlag,10879,https://v2.sherpa.ac.uk/id/publisher_policy/257,2010-08-24 13:51:41,2022-05-10 09:39:56
49531,413645,Zentralblatt für Chirurgie,NaN,0044-409X,https://www.thieme-connect.com/products/ejourn...,257,de,commercial_publisher,http://www.thieme.de/,Georg Thieme Verlag,10884,https://v2.sherpa.ac.uk/id/publisher_policy/257,2010-08-24 13:58:20,2022-09-21 14:14:30
49534,9435608,Zoology,NaN,0944-2006,http://www.elsevier.com/wps/product/cws_home/7...,30,us,commercial_publisher,http://www.elsevier.com/,Elsevier,15919,https://v2.sherpa.ac.uk/id/publisher_policy/2943,2010-09-14 14:06:06,2022-07-26 14:26:43

In [33]:
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN,sherpa_has_oa_path,embargo,embargo_published_version,embargo_accepted_version,sherpa_oa_green,additional_oa_fee,sherpa_id
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674,yes,24.0,NaN,24.0,yes,yes,1406.0
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776,yes,NaN,NaN,NaN,NaN,NaN,10921.0
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416,yes,12.0,NaN,12.0,yes,yes,16180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720,yes,12.0,NaN,12.0,yes,yes,15919.0
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378,yes,12.0,NaN,12.0,yes,yes,2555.0
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334,yes,NaN,NaN,NaN,NaN,yes,6.0
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730,yes,6.0,NaN,6.0,yes,yes,2242.0

In [34]:
# final merge
pubmed = pd.merge(pubmed, sherpa_policies_dedup, on='NlmUniqueID', how='left')
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN,sherpa_has_oa_path,embargo,embargo_published_version,embargo_accepted_version,sherpa_oa_green,additional_oa_fee,sherpa_id_x,title_sherpa,issne_sherpa,issnp_sherpa,url,publisher_id,publisher_country,publisher_type,publisher_url,publisher_name,sherpa_id_y,sherpa_uri,sherpa_created,sherpa_last_modified
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674,yes,24.0,NaN,24.0,yes,yes,1406.0,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55.0,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,1406.0,https://v2.sherpa.ac.uk/id/publisher_policy/1112,2010-07-15 16:04:39,2022-07-26 10:25:23
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776,yes,NaN,NaN,NaN,NaN,NaN,10921.0,AACN Advanced Critical Care,1559-7776,1559-7768,http://acc.aacnjournals.org/,663.0,us,society_publisher,https://www.aacn.org/,American Association of Critical Care Nurses,10921.0,https://v2.sherpa.ac.uk/id/publisher_policy/663,2010-08-24 15:05:09,2022-07-08 08:42:33
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416,yes,12.0,NaN,12.0,yes,yes,16180.0,AAPS Journal,NaN,1550-7416,http://link.springer.com/journal/12248,313.0,us,client_organisation,https://www.aaps.org/home,American Association of Pharmaceutical Scientists,16180.0,https://v2.sherpa.ac.uk/id/publisher_policy/3291,2010-09-15 13:16:19,2023-01-05 14:55:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720,yes,12.0,NaN,12.0,yes,yes,15919.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378,yes,12.0,NaN,12.0,yes,yes,2555.0,Zoonoses and Public Health,1863-2378,1863-1959,https://onlinelibrary.wiley.com/journal/18632378,580.0,us,commercial_publisher,https://www.wiley.com/en-gb,Wiley,2555.0,https://v2.sherpa.ac.uk/id/publisher_policy/2050,2010-07-20 14:58:33,2022-07-27 12:37:58
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334,yes,NaN,NaN,NaN,NaN,yes,6.0,Zootaxa,1175-5334,1175-5326,https://www.mapress.com/zt/,284.0,nz,commercial_publisher,https://www.mapress.com/,Magnolia Press,6.0,https://v2.sherpa.ac.uk/id/publisher_policy/284,2010-06-30 17:47:50,2022-07-15 08:53:17
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730,yes,6.0,NaN,6.0,yes,yes,2242.0,Zygote,1469-8730,0967-1994,http://journals.cambridge.org/action/displayJo...,27.0,gb,university_publisher,https://www.cambridge.org/,Cambridge University Press,2242.0,https://v2.sherpa.ac.uk/id/publisher_policy/5000,2010-07-19 16:07:37,2022-06-16 13:58:04

In [35]:
# check sherpa id not equal
pubmed.loc[(pubmed['sherpa_id_x'].notna()) & (pubmed['sherpa_id_y'].notna()) & (pubmed['sherpa_id_x'] != pubmed['sherpa_id_y'])]

Empty DataFrame
Columns: [NlmUniqueID, Title, MedlineTA, Country, Place, Publisher, PublicationFirstYear, PublicationEndYear, Frequency, ISSN-Electronic, ISSN-Print, ISSN-Linking, Language, TitleContinuationYN, IndexingStartDate, CurrentlyIndexedYN, IndexOnlineYN, IndexingSubset, IndexingSelectedURL, ReportedMedlineYN, ISSN, sherpa_has_oa_path, embargo, embargo_published_version, embargo_accepted_version, sherpa_oa_green, additional_oa_fee, sherpa_id_x, title_sherpa, issne_sherpa, issnp_sherpa, url, publisher_id, publisher_country, publisher_type, publisher_url, publisher_name, sherpa_id_y, sherpa_uri, sherpa_created, sherpa_last_modified]
Index: []

In [36]:
# keep all sherpa ids
pubmed['sherpa_id'] = pubmed['sherpa_id_x']
pubmed.loc[pubmed['sherpa_id'].isna(), 'sherpa_id'] = pubmed['sherpa_id_y']
del pubmed['sherpa_id_x']
del pubmed['sherpa_id_y']
pubmed

,NlmUniqueID,Title,MedlineTA,Country,Place,Publisher,PublicationFirstYear,PublicationEndYear,Frequency,ISSN-Electronic,ISSN-Print,ISSN-Linking,Language,TitleContinuationYN,IndexingStartDate,CurrentlyIndexedYN,IndexOnlineYN,IndexingSubset,IndexingSelectedURL,ReportedMedlineYN,ISSN,sherpa_has_oa_path,embargo,embargo_published_version,embargo_accepted_version,sherpa_oa_green,additional_oa_fee,title_sherpa,issne_sherpa,issnp_sherpa,url,publisher_id,publisher_country,publisher_type,publisher_url,publisher_name,sherpa_uri,sherpa_created,sherpa_last_modified,sherpa_id
0,9015384,20 century British history,20 Century Br Hist,England,"Eynsham, Oxford",Oxford University Press,1990,NaN,"4 no. a year,",1477-4674,0955-2359,0955-2359,eng,N,1990.0,Y,N,QIS,NaN,Y,1477-4674,yes,24.0,NaN,24.0,yes,yes,Twentieth Century British History,1477-4674,0955-2359,https://academic.oup.com/tcbh,55.0,gb,university_publisher,https://academic.oup.com/journals/,Oxford University Press,https://v2.sherpa.ac.uk/id/publisher_policy/1112,2010-07-15 16:04:39,2022-07-26 10:25:23,1406.0
1,101714112,A&A practice,A A Pract,United States,"[Philadelphia, PA]","Wolters Kluwer Health, Inc.",2018,NaN,Biweekly,2575-3126,NaN,2575-3126,eng,Y,2018.0,Y,Y,IM,https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=...,Y,2575-3126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101269322,AACN advanced critical care,AACN Adv Crit Care,United States,"Aliso Viejo, CA",American Association of Critical-Care Nurses (...,2006,NaN,Quarterly,1559-7776,1559-7768,1559-7768,eng,Y,2006.0,Y,Y,N,https://aacnjournals.org/aacnacconline,Y,1559-7776,yes,NaN,NaN,NaN,NaN,NaN,AACN Advanced Critical Care,1559-7776,1559-7768,http://acc.aacnjournals.org/,663.0,us,society_publisher,https://www.aacn.org/,American Association of Critical Care Nurses,https://v2.sherpa.ac.uk/id/publisher_policy/663,2010-08-24 15:05:09,2022-07-08 08:42:33,10921.0
3,0431420,AANA journal,AANA J,United States,"Park Ridge, Ill.",American Association of Nurse Anesthetists,1974,NaN,Bimonthly,2162-5239,0094-6354,0094-6354,eng,N,1974.0,Y,Y,N,https://www.aana.com/publications/aana-journal,Y,2162-5239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101223209,The AAPS journal,AAPS J,United States,"Arlington, Va., USA",American Association of Pharmaceutical Scientists,2004,NaN,Four no. a year,1550-7416,NaN,1550-7416,eng,Y,2004.0,Y,Y,IM,https://link.springer.com/journal/12248,Y,1550-7416,yes,12.0,NaN,12.0,yes,yes,AAPS Journal,NaN,1550-7416,http://link.springer.com/journal/12248,313.0,us,client_organisation,https://www.aaps.org/home,American Association of Pharmaceutical Scientists,https://v2.sherpa.ac.uk/id/publisher_policy/3291,2010-09-15 13:16:19,2023-01-05 14:55:40,16180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5274,8702287,Zoological science,Zoolog Sci,Japan,"Tokyo, Japan",Zoological Society of Japan,1984,NaN,"Monthly,",NaN,0289-0003,0289-0003,eng,N,2002.0,Y,Y,IM,http://www.bioone.org/loi/jzoo,Y,0289-0003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5275,9435608,"Zoology (Jena, Germany)",Zoology (Jena),Germany,"Jena, Germany",Urban & Fischer,1994,NaN,"Six no. a year,",1873-2720,0944-2006,0944-2006,eng,N,2005.0,Y,Y,IM,https://www.sciencedirect.com/journal/zoology,Y,1873-2720,yes,12.0,NaN,12.0,yes,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15919.0
5276,101300786,Zoonoses and public health,Zoonoses Public Health,Germany,"Berlin, Germany",Blackwell Verlag,2007,NaN,Ten no. a year,1863-2378,1863-1959,1863-1959,eng,Y,2007.0,Y,Y,IM,http://onlinelibrary.wiley.com/journal/10.1111...,Y,1863-2378,yes,12.0,NaN,12.0,yes,yes,Zoonoses and Public Health,1863-2378,1863-1959,https://onlinelibrary.wiley.com/journal/18632378,580.0,us,commercial_publisher,https://www.wiley.com/en-gb,Wiley,https://v2.sherpa.ac.uk/id/publisher_policy/2050,2010-07-20 14:58:33,2022-07-27 12:37:58,2555.0
5277,101179386,Zootaxa,Zootaxa,New Zealand,"Auckland, N.Z.",Magnolia Press,2001,NaN,Irregular,1175-5334,1175-5326,1175-5326,eng,N,2013.0,Y,Y,IM,http://www.mapress.com/j/zt/,Y,1175-5334,yes,NaN,NaN,NaN,NaN,yes,Zootaxa,1175-5334,1175-5326,https://www.mapress.com/zt/,284.0,nz,commercial_publisher,https://www.mapress.com/,Magnolia Press,https://v2.sherpa.ac.uk/id/publisher_policy/284,2010-06-30 17:47:50,2022-07-15 08:53:17,6.0
5278,9309124,"Zygote (Cambridge, England)",Zygote,England,"Cambridge ; New York, NY",Cambridge University Press,1993,NaN,"Quarterly,",1469-8730,0967-1994,0967-1994,eng,N,1993.0,Y,Y,IM,https://www.cambridge.org/core/journals/zygote,Y,1469-8730,yes,6.0,NaN,6.0,yes,yes,Zygote,1469-8730,0967-1994,http://journals.cambridge.org/action/displayJo...,27.0,gb,university_publisher,https://www.cambridge.org/,Cambridge University Press,https://v2.sherpa.ac.uk/id/publisher_policy/5000,2010-07-19 16:07:37,2022-06-16 13:58:04,2242.0

## Adding OA data to MeSH

In [37]:
MeshHeadings = pd.read_csv('data/sources/nlm/lsi2023_MeshHeadings.tsv', encoding='utf-8', header=0, sep='\t')
MeshHeadings

      NlmUniqueID            MeshHeading  Unnamed: 2
0         9015384                History         NaN
1         9015384         United Kingdom         NaN
2       101637720         Anesthesiology         NaN
3       101714112         Anesthesiology         NaN
4       101269322          Critical Care         NaN
...           ...                    ...         ...
26785   21830020R    History of Medicine         NaN
26786     0233767              Dentistry         NaN
26787     9309124  Embryonic Development         NaN
26788     9309124      Fetal Development         NaN
26789     9309124                 Zygote         NaN

[26790 rows x 3 columns]

In [38]:
BroadJournalHeadings = pd.read_csv('data/sources/nlm/lsi2023_BroadJournalHeadings.tsv', encoding='utf-8', header=0, sep='\t')
BroadJournalHeadings

      NlmUniqueID    BroadJournalHeading  Unnamed: 2
0         9015384    History of Medicine         NaN
1       101637720         Anesthesiology         NaN
2       101714112         Anesthesiology         NaN
3       101269322          Critical Care         NaN
4       101269322                Nursing         NaN
...           ...                    ...         ...
16386     0056272  Reproductive Medicine         NaN
16387     0056272    Veterinary Medicine         NaN
16388   21830020R    History of Medicine         NaN
16389     0233767              Dentistry         NaN
16390     9309124             Embryology         NaN

[16391 rows x 3 columns]

In [39]:
# clean last column
del MeshHeadings['Unnamed: 2']
del BroadJournalHeadings['Unnamed: 2']

In [40]:
# oa, green and hybrid  merge
MeshHeadings = pd.merge(MeshHeadings, sherpa_oa, on='NlmUniqueID', how='left')
MeshHeadings = pd.merge(MeshHeadings, sherpa_green, on='NlmUniqueID', how='left')
MeshHeadings = MeshHeadings.rename(columns={'oa_status' : 'sherpa_oa_green'})
MeshHeadings.loc[(MeshHeadings['sherpa_oa_green'] == 'green'), 'sherpa_oa_green'] = 'yes'
MeshHeadings = pd.merge(MeshHeadings, sherpa_hybrid, on='NlmUniqueID', how='left')
MeshHeadings = MeshHeadings.rename(columns={'oa_status' : 'sherpa_oa_hybrid'})
# MeshHeadings.loc[(MeshHeadings['sherpa_oa_hybrid'] == 'hybrid'), 'sherpa_oa_hybrid'] = 'yes'
MeshHeadings

,NlmUniqueID,MeshHeading,sherpa_id_x,sherpa_has_oa_path,embargo,sherpa_id_y,embargo_published_version,embargo_accepted_version,sherpa_oa_green,sherpa_id,additional_oa_fee,sherpa_oa_hybrid
0,9015384,History,1406.0,yes,24.0,1406.0,NaN,24.0,yes,1406.0,yes,hybrid or gold
1,9015384,United Kingdom,1406.0,yes,24.0,1406.0,NaN,24.0,yes,1406.0,yes,hybrid or gold
2,101637720,Anesthesiology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,101714112,Anesthesiology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101269322,Critical Care,10921.0,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
26785,21830020R,History of Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26786,0233767,Dentistry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26787,9309124,Embryonic Development,2242.0,yes,6.0,2242.0,NaN,6.0,yes,2242.0,yes,hybrid or gold
26788,9309124,Fetal Development,2242.0,yes,6.0,2242.0,NaN,6.0,yes,2242.0,yes,hybrid or gold
26789,9309124,Zygote,2242.0,yes,6.0,2242.0,NaN,6.0,yes,2242.0,yes,hybrid or gold

In [41]:
# oa, green and hybrid  merge
BroadJournalHeadings = pd.merge(BroadJournalHeadings, sherpa_oa, on='NlmUniqueID', how='left')
BroadJournalHeadings = pd.merge(BroadJournalHeadings, sherpa_green, on='NlmUniqueID', how='left')
BroadJournalHeadings = BroadJournalHeadings.rename(columns={'oa_status' : 'sherpa_oa_green'})
BroadJournalHeadings.loc[(BroadJournalHeadings['sherpa_oa_green'] == 'green'), 'sherpa_oa_green'] = 'yes'
BroadJournalHeadings = pd.merge(BroadJournalHeadings, sherpa_hybrid, on='NlmUniqueID', how='left')
BroadJournalHeadings = BroadJournalHeadings.rename(columns={'oa_status' : 'sherpa_oa_hybrid'})
# BroadJournalHeadings.loc[(BroadJournalHeadings['sherpa_oa_hybrid'] == 'hybrid'), 'sherpa_oa_hybrid'] = 'yes'
BroadJournalHeadings

,NlmUniqueID,BroadJournalHeading,sherpa_id_x,sherpa_has_oa_path,embargo,sherpa_id_y,embargo_published_version,embargo_accepted_version,sherpa_oa_green,sherpa_id,additional_oa_fee,sherpa_oa_hybrid
0,9015384,History of Medicine,1406.0,yes,24.0,1406.0,NaN,24.0,yes,1406.0,yes,hybrid or gold
1,101637720,Anesthesiology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101714112,Anesthesiology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,101269322,Critical Care,10921.0,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101269322,Nursing,10921.0,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16386,0056272,Reproductive Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16387,0056272,Veterinary Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16388,21830020R,History of Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16389,0233767,Dentistry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16390,9309124,Embryology,2242.0,yes,6.0,2242.0,NaN,6.0,yes,2242.0,yes,hybrid or gold

## Counts

In [42]:
pubmed.shape[0]

5279

In [43]:
# journals in Sherpa
pubmed.loc[pubmed['sherpa_id'].notna()].shape[0]

4371

In [44]:
# journals in Sherpa % 
pubmed.loc[pubmed['sherpa_id'].notna()].shape[0] / pubmed.shape[0]

0.827997726842205

In [45]:
# journals not in Sherpa
pubmed.loc[pubmed['sherpa_id'].isna()].shape[0]

908

In [46]:
# journals not in Sherpa % 
pubmed.loc[pubmed['sherpa_id'].isna()].shape[0] / pubmed.shape[0]

0.17200227315779504

In [47]:
# sherpa OA
pubmed['sherpa_has_oa_path'].value_counts()

yes    4371
Name: sherpa_has_oa_path, dtype: int64

In [48]:
# not oa
pubmed.loc[pubmed['sherpa_has_oa_path'] != 'yes'].shape[0]

908

In [49]:
# journals in sherpa and not oa
pubmed.loc[(pubmed['sherpa_id'].notna()) & (pubmed['sherpa_has_oa_path'] != 'yes')].shape[0]

0

In [50]:
# sherpa green
pubmed['sherpa_oa_green'].value_counts()

yes    4275
Name: sherpa_oa_green, dtype: int64

In [51]:
# sherpa green % 
pubmed.loc[pubmed['sherpa_oa_green'] == 'yes'].shape[0]  / pubmed.shape[0]

0.8098124644819095

In [52]:
# sherpa embargoes
pubmed['embargo'].value_counts()

12.0    2442
0.0     1579
6.0      185
24.0      40
18.0      29
Name: embargo, dtype: int64

In [53]:
# sherpa green with embargo known
pubmed.loc[pubmed['embargo'] > 0].shape[0]  / pubmed.loc[pubmed['sherpa_oa_green'] == 'yes'].shape[0]

0.6306432748538011

In [54]:
# sherpa additional oa fees
pubmed['additional_oa_fee'].value_counts()

yes    3418
Name: additional_oa_fee, dtype: int64

In [55]:
# sherpa additional oa fee % 
pubmed.loc[pubmed['additional_oa_fee'] == 'yes'].shape[0]  / pubmed.shape[0]

0.6474711119530214

In [56]:
# oa not green
pubmed.loc[(pubmed['sherpa_has_oa_path'] == 'yes') & (pubmed['sherpa_oa_green'] != 'yes')].shape[0]

96

In [57]:
# oa not additional_oa_fee
pubmed.loc[(pubmed['sherpa_has_oa_path'] == 'yes') & (pubmed['additional_oa_fee'] != 'yes')].shape[0]

953

In [58]:
# green and additional_oa_fee
pubmed.loc[(pubmed['sherpa_oa_green'] == 'yes') & (pubmed['additional_oa_fee'] == 'yes')].shape[0]

3372

In [59]:
# additional_oa_fee not green
pubmed.loc[(pubmed['additional_oa_fee'] == 'yes') & (pubmed['sherpa_oa_green'] != 'yes')].shape[0]

46

In [60]:
#  green not additional_oa_fee
pubmed.loc[(pubmed['sherpa_oa_green'] == 'yes') & (pubmed['additional_oa_fee'] != 'yes')].shape[0]

903

In [61]:
# oa not additional_oa_fee not green
pubmed.loc[(pubmed['sherpa_has_oa_path'] == 'yes') & (pubmed['sherpa_oa_green'] != 'yes') & (pubmed['additional_oa_fee'] != 'yes')].shape[0]

50

## Exports

In [62]:
# exports csv
pubmed.to_csv('data/temp/2023/merge_pubmed_sherpa.tsv', sep='\t', encoding='utf-8', index=False)
MeshHeadings.to_csv('data/temp/2023/merge_MeshHeadings_sherpa.tsv', sep='\t', encoding='utf-8', index=False)
BroadJournalHeadings.to_csv('data/temp/2023/merge_BroadJournalHeadings_sherpa.tsv', sep='\t', encoding='utf-8', index=False)

In [63]:
# exports excel
pubmed.to_excel('data/temp/2023/merge_pubmed_sherpa.xlsx', index=False)
MeshHeadings.to_excel('data/temp/2023/merge_MeshHeadings_sherpa.xlsx', index=False)
BroadJournalHeadings.to_excel('data/temp/2023/merge_BroadJournalHeadings_sherpa.xlsx', index=False)